name: Deploy Workflow
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install pylint
        run: pip install pylint
      - name: Do Tests
        run: pylint .
  deploy:
    needs: tests # with this statement the 'deploy' job waits for 'tests' to finish
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Deploying..."